# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.29.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.29.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/fangke/Downloads/HW1_Sprouthon_Mac

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/fangke/Downloads/HW1_Sprouthon_Mac/build

# Include any dependencies generated for this target.
include CMakeFiles/Sprouthon.dir/depend.make
# Include any dependencies generated by the compiler for this target.
include CMakeFiles/Sprouthon.dir/compiler_depend.make

# Include the progress variables for this target.
include CMakeFiles/Sprouthon.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/Sprouthon.dir/flags.make

CMakeFiles/Sprouthon.dir/src/main.cpp.o: CMakeFiles/Sprouthon.dir/flags.make
CMakeFiles/Sprouthon.dir/src/main.cpp.o: /Users/fangke/Downloads/HW1_Sprouthon_Mac/src/main.cpp
CMakeFiles/Sprouthon.dir/src/main.cpp.o: CMakeFiles/Sprouthon.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/fangke/Downloads/HW1_Sprouthon_Mac/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object CMakeFiles/Sprouthon.dir/src/main.cpp.o"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Sprouthon.dir/src/main.cpp.o -MF CMakeFiles/Sprouthon.dir/src/main.cpp.o.d -o CMakeFiles/Sprouthon.dir/src/main.cpp.o -c /Users/fangke/Downloads/HW1_Sprouthon_Mac/src/main.cpp

CMakeFiles/Sprouthon.dir/src/main.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/Sprouthon.dir/src/main.cpp.i"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/fangke/Downloads/HW1_Sprouthon_Mac/src/main.cpp > CMakeFiles/Sprouthon.dir/src/main.cpp.i

CMakeFiles/Sprouthon.dir/src/main.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/Sprouthon.dir/src/main.cpp.s"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/fangke/Downloads/HW1_Sprouthon_Mac/src/main.cpp -o CMakeFiles/Sprouthon.dir/src/main.cpp.s

CMakeFiles/Sprouthon.dir/src/scoreboard.cpp.o: CMakeFiles/Sprouthon.dir/flags.make
CMakeFiles/Sprouthon.dir/src/scoreboard.cpp.o: /Users/fangke/Downloads/HW1_Sprouthon_Mac/src/scoreboard.cpp
CMakeFiles/Sprouthon.dir/src/scoreboard.cpp.o: CMakeFiles/Sprouthon.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/fangke/Downloads/HW1_Sprouthon_Mac/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Building CXX object CMakeFiles/Sprouthon.dir/src/scoreboard.cpp.o"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Sprouthon.dir/src/scoreboard.cpp.o -MF CMakeFiles/Sprouthon.dir/src/scoreboard.cpp.o.d -o CMakeFiles/Sprouthon.dir/src/scoreboard.cpp.o -c /Users/fangke/Downloads/HW1_Sprouthon_Mac/src/scoreboard.cpp

CMakeFiles/Sprouthon.dir/src/scoreboard.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/Sprouthon.dir/src/scoreboard.cpp.i"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/fangke/Downloads/HW1_Sprouthon_Mac/src/scoreboard.cpp > CMakeFiles/Sprouthon.dir/src/scoreboard.cpp.i

CMakeFiles/Sprouthon.dir/src/scoreboard.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/Sprouthon.dir/src/scoreboard.cpp.s"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/fangke/Downloads/HW1_Sprouthon_Mac/src/scoreboard.cpp -o CMakeFiles/Sprouthon.dir/src/scoreboard.cpp.s

CMakeFiles/Sprouthon.dir/src/python.cpp.o: CMakeFiles/Sprouthon.dir/flags.make
CMakeFiles/Sprouthon.dir/src/python.cpp.o: /Users/fangke/Downloads/HW1_Sprouthon_Mac/src/python.cpp
CMakeFiles/Sprouthon.dir/src/python.cpp.o: CMakeFiles/Sprouthon.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/fangke/Downloads/HW1_Sprouthon_Mac/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Building CXX object CMakeFiles/Sprouthon.dir/src/python.cpp.o"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Sprouthon.dir/src/python.cpp.o -MF CMakeFiles/Sprouthon.dir/src/python.cpp.o.d -o CMakeFiles/Sprouthon.dir/src/python.cpp.o -c /Users/fangke/Downloads/HW1_Sprouthon_Mac/src/python.cpp

CMakeFiles/Sprouthon.dir/src/python.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/Sprouthon.dir/src/python.cpp.i"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/fangke/Downloads/HW1_Sprouthon_Mac/src/python.cpp > CMakeFiles/Sprouthon.dir/src/python.cpp.i

CMakeFiles/Sprouthon.dir/src/python.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/Sprouthon.dir/src/python.cpp.s"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/fangke/Downloads/HW1_Sprouthon_Mac/src/python.cpp -o CMakeFiles/Sprouthon.dir/src/python.cpp.s

CMakeFiles/Sprouthon.dir/src/grid.cpp.o: CMakeFiles/Sprouthon.dir/flags.make
CMakeFiles/Sprouthon.dir/src/grid.cpp.o: /Users/fangke/Downloads/HW1_Sprouthon_Mac/src/grid.cpp
CMakeFiles/Sprouthon.dir/src/grid.cpp.o: CMakeFiles/Sprouthon.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/fangke/Downloads/HW1_Sprouthon_Mac/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_4) "Building CXX object CMakeFiles/Sprouthon.dir/src/grid.cpp.o"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Sprouthon.dir/src/grid.cpp.o -MF CMakeFiles/Sprouthon.dir/src/grid.cpp.o.d -o CMakeFiles/Sprouthon.dir/src/grid.cpp.o -c /Users/fangke/Downloads/HW1_Sprouthon_Mac/src/grid.cpp

CMakeFiles/Sprouthon.dir/src/grid.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/Sprouthon.dir/src/grid.cpp.i"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/fangke/Downloads/HW1_Sprouthon_Mac/src/grid.cpp > CMakeFiles/Sprouthon.dir/src/grid.cpp.i

CMakeFiles/Sprouthon.dir/src/grid.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/Sprouthon.dir/src/grid.cpp.s"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/fangke/Downloads/HW1_Sprouthon_Mac/src/grid.cpp -o CMakeFiles/Sprouthon.dir/src/grid.cpp.s

CMakeFiles/Sprouthon.dir/src/game.cpp.o: CMakeFiles/Sprouthon.dir/flags.make
CMakeFiles/Sprouthon.dir/src/game.cpp.o: /Users/fangke/Downloads/HW1_Sprouthon_Mac/src/game.cpp
CMakeFiles/Sprouthon.dir/src/game.cpp.o: CMakeFiles/Sprouthon.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/fangke/Downloads/HW1_Sprouthon_Mac/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_5) "Building CXX object CMakeFiles/Sprouthon.dir/src/game.cpp.o"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Sprouthon.dir/src/game.cpp.o -MF CMakeFiles/Sprouthon.dir/src/game.cpp.o.d -o CMakeFiles/Sprouthon.dir/src/game.cpp.o -c /Users/fangke/Downloads/HW1_Sprouthon_Mac/src/game.cpp

CMakeFiles/Sprouthon.dir/src/game.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/Sprouthon.dir/src/game.cpp.i"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/fangke/Downloads/HW1_Sprouthon_Mac/src/game.cpp > CMakeFiles/Sprouthon.dir/src/game.cpp.i

CMakeFiles/Sprouthon.dir/src/game.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/Sprouthon.dir/src/game.cpp.s"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/fangke/Downloads/HW1_Sprouthon_Mac/src/game.cpp -o CMakeFiles/Sprouthon.dir/src/game.cpp.s

CMakeFiles/Sprouthon.dir/src/apple.cpp.o: CMakeFiles/Sprouthon.dir/flags.make
CMakeFiles/Sprouthon.dir/src/apple.cpp.o: /Users/fangke/Downloads/HW1_Sprouthon_Mac/src/apple.cpp
CMakeFiles/Sprouthon.dir/src/apple.cpp.o: CMakeFiles/Sprouthon.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/Users/fangke/Downloads/HW1_Sprouthon_Mac/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_6) "Building CXX object CMakeFiles/Sprouthon.dir/src/apple.cpp.o"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/Sprouthon.dir/src/apple.cpp.o -MF CMakeFiles/Sprouthon.dir/src/apple.cpp.o.d -o CMakeFiles/Sprouthon.dir/src/apple.cpp.o -c /Users/fangke/Downloads/HW1_Sprouthon_Mac/src/apple.cpp

CMakeFiles/Sprouthon.dir/src/apple.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/Sprouthon.dir/src/apple.cpp.i"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/fangke/Downloads/HW1_Sprouthon_Mac/src/apple.cpp > CMakeFiles/Sprouthon.dir/src/apple.cpp.i

CMakeFiles/Sprouthon.dir/src/apple.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/Sprouthon.dir/src/apple.cpp.s"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/fangke/Downloads/HW1_Sprouthon_Mac/src/apple.cpp -o CMakeFiles/Sprouthon.dir/src/apple.cpp.s

# Object files for target Sprouthon
Sprouthon_OBJECTS = \
"CMakeFiles/Sprouthon.dir/src/main.cpp.o" \
"CMakeFiles/Sprouthon.dir/src/scoreboard.cpp.o" \
"CMakeFiles/Sprouthon.dir/src/python.cpp.o" \
"CMakeFiles/Sprouthon.dir/src/grid.cpp.o" \
"CMakeFiles/Sprouthon.dir/src/game.cpp.o" \
"CMakeFiles/Sprouthon.dir/src/apple.cpp.o"

# External object files for target Sprouthon
Sprouthon_EXTERNAL_OBJECTS =

Sprouthon: CMakeFiles/Sprouthon.dir/src/main.cpp.o
Sprouthon: CMakeFiles/Sprouthon.dir/src/scoreboard.cpp.o
Sprouthon: CMakeFiles/Sprouthon.dir/src/python.cpp.o
Sprouthon: CMakeFiles/Sprouthon.dir/src/grid.cpp.o
Sprouthon: CMakeFiles/Sprouthon.dir/src/game.cpp.o
Sprouthon: CMakeFiles/Sprouthon.dir/src/apple.cpp.o
Sprouthon: CMakeFiles/Sprouthon.dir/build.make
Sprouthon: /usr/local/lib/libsfml-graphics.2.6.1.dylib
Sprouthon: /usr/local/lib/libsfml-window.2.6.1.dylib
Sprouthon: /usr/local/lib/libsfml-system.2.6.1.dylib
Sprouthon: CMakeFiles/Sprouthon.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --bold --progress-dir=/Users/fangke/Downloads/HW1_Sprouthon_Mac/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_7) "Linking CXX executable Sprouthon"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/Sprouthon.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/Sprouthon.dir/build: Sprouthon
.PHONY : CMakeFiles/Sprouthon.dir/build

CMakeFiles/Sprouthon.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/Sprouthon.dir/cmake_clean.cmake
.PHONY : CMakeFiles/Sprouthon.dir/clean

CMakeFiles/Sprouthon.dir/depend:
	cd /Users/fangke/Downloads/HW1_Sprouthon_Mac/build && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /Users/fangke/Downloads/HW1_Sprouthon_Mac /Users/fangke/Downloads/HW1_Sprouthon_Mac /Users/fangke/Downloads/HW1_Sprouthon_Mac/build /Users/fangke/Downloads/HW1_Sprouthon_Mac/build /Users/fangke/Downloads/HW1_Sprouthon_Mac/build/CMakeFiles/Sprouthon.dir/DependInfo.cmake "--color=$(COLOR)"
.PHONY : CMakeFiles/Sprouthon.dir/depend

